/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package neto.kotlintests

class App {
    val greeting: String
        get() = "Hello World!"
}

fun main() {
    println(App().greeting)
}
